apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Monkey D. Luffys
  description: Strawhat Pirates Captains! 
  links:
    - url: abola.pt
      title: futebol
      icon: dashboard
spec:
  type: application
  lifecycle: production
